# Generated by Django 5.1.2 on 2024-11-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="image",
            field=models.ImageField(upload_to="flowers/"),
        ),
    ]
