# Generated by Django 5.1.2 on 2024-11-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0002_alter_flower_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
