# Generated by Django 5.1.2 on 2025-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0003_alter_flower_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="Uses",
            field=models.TextField(blank=True, null=True),
        ),
    ]
